---

web_favicon_url: assets/ndkprd.png
web_profile_image_url: assets/ndkprd.png
web_headline: Hi, Andhika here.
web_descriptions:
  - "a devops/sre/observability/platform engineering enthusiast who's currently working as a network security engineer at maritime and logistic company in indonesia."
  - "feel free to connect with me below! I'm always open to discussions and new opportunities."
web_footer: "© 2025 ndkprd"
web_links:
  - name: blog
    url: https://blog.ndkprd.com
  - name: gitlab
    url: https://gitlab.com/endekasoft
  - name: linkedin
    url: https://linkedin.com/in/ndkprd
  - name: x (formerly twitter)
    url: https://x.com/ndkprd
  - name: instagram
    url: https://instagram.com/ndkprd
